# Generated by Django 5.0 on 2024-01-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0002_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='date_time',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
