# Generated by Django 5.0 on 2024-01-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_about_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='name',
            new_name='u_name',
        ),
    ]
